import { useAnalysis } from '../AnalysisContext'
import EmptyState from '../components/EmptyState'

function pct(v, digits = 1) { return v != null ? (v * 100).toFixed(digits) + '%' : '—' }
function eur(v) {
  if (v == null) return '—'
  if (Math.abs(v) >= 1e9) return '€' + (v / 1e9).toFixed(2) + 'B'
  if (Math.abs(v) >= 1e6) return '€' + (v / 1e6).toFixed(1) + 'M'
  return '€' + v.toFixed(0)
}

function buildNarrative({ liq, stress, redemption, waterfall }) {
  if (!liq) return ''
  const m = liq.liquidity_metrics
  const stressResults = stress?.stress_results || []
  const worst = stressResults.length
    ? stressResults.reduce((a, b) => (b.nav_impact_pct < a.nav_impact_pct ? b : a), stressResults[0])
    : null
  const normalRed = redemption?.redemption_results || []
  const r20 = normalRed.find((r) => Math.abs(r.scenario_pct - 0.2) < 0.01)
  const wfMeta = waterfall?.waterfall_meta || {}

  const flagLine = m.breach_flag
    ? `⚠️  BREACH: The fund's liquid assets fall below the regulatory breach threshold.`
    : m.warning_flag
    ? `⚠️  WARNING: The fund's liquidity profile is approaching the warning threshold.`
    : `✅  The fund's liquidity profile is within normal parameters.`

  return `LIQUIDITY RISK NARRATIVE — ${liq.fund_name}
Reporting Date: ${liq.reporting_date}   |   Total NAV: ${eur(liq.total_nav_eur)}

${flagLine}

──────────────────────────────────────────
1. LIQUIDITY PROFILE
──────────────────────────────────────────
T+1 Liquidity Coverage Ratio : ${pct(m.lcr_t1)}
T+3 Liquidity Coverage Ratio : ${pct(m.lcr_t3)}
T+7 Liquidity Coverage Ratio : ${pct(m.lcr_t7)}
Illiquid assets (>T+7)       : ${pct(m.illiquid_pct)}
Days to liquidate 50% NAV    : ${m.days_to_50pct?.toFixed(1) ?? '—'}
Days to liquidate 75% NAV    : ${m.days_to_75pct?.toFixed(1) ?? '—'}
Days to liquidate 90% NAV    : ${m.days_to_90pct?.toFixed(1) ?? '—'}
Top-10 investor concentration: ${pct(m.top10_concentration)}
Liquidity / concentration    : ${m.liquidity_vs_concentration?.toFixed(2) ?? '—'}x

──────────────────────────────────────────
2. STRESS TESTING
──────────────────────────────────────────
${stressResults.length} ESMA-style scenarios were run.
${worst ? `Worst-case scenario: "${worst.scenario_name}"
  NAV impact : ${pct(worst.nav_impact_pct)} (${eur(worst.nav_impact_eur)})
  Equity loss: ${eur(worst.equity_loss_eur)}
  Credit loss: ${eur(worst.credit_loss_eur)}
  Liquidity after shock: ${pct(worst.liquid_pct_after)} (from ${pct(worst.liquid_pct_before)})
  Days to liquidate: ${worst.time_to_liquidate_days?.toFixed(1) ?? '—'}
  Can meet redemption: ${worst.can_meet_redemption ? 'Yes' : 'No'}` : 'No stress results available.'}

──────────────────────────────────────────
3. REDEMPTION COVERAGE
──────────────────────────────────────────
${normalRed.map((r) =>
  `  ${pct(r.scenario_pct)} redemption: ` +
  `Liquidity ${pct(r.liquidity_available_pct)}, ` +
  `Shortfall ${r.shortfall_eur > 0 ? eur(r.shortfall_eur) : 'None'}, ` +
  `T+1: ${r.can_meet_t1 ? 'Met' : 'Not met'}, ` +
  `Gate: ${r.gate_triggered ? 'Triggered' : 'No'}`
).join('\n') || 'No redemption results.'}

──────────────────────────────────────────
4. WATERFALL — WORST-CASE LIQUIDATION
──────────────────────────────────────────
Target                : ${eur(wfMeta.target_eur)}
Total proceeds        : ${eur(wfMeta.total_proceeds_eur)}
Target met            : ${wfMeta.target_met ? 'Yes' : 'No'}
Days to target        : ${wfMeta.days_to_target?.toFixed(1) ?? '—'}
Residual shortfall    : ${eur(wfMeta.residual_shortfall_eur)}
NAV impact (sell-down): ${wfMeta.nav_impact_pct != null ? (wfMeta.nav_impact_pct * 100).toFixed(2) + '%' : '—'}

──────────────────────────────────────────
Generated by Liquidity Risk Tool v1.1
`
}

export default function RiskStory() {
  const { data } = useAnalysis()
  const liq = data?.liquidity
  if (!liq) return <EmptyState />

  const narrative = buildNarrative({
    liq,
    stress: data.stress,
    redemption: data.redemption,
    waterfall: data.waterfall,
  })

  function copy() { navigator.clipboard.writeText(narrative) }

  function downloadJSON() {
    const blob = new Blob([JSON.stringify({ ...data }, null, 2)], { type: 'application/json' })
    const url = URL.createObjectURL(blob)
    const a = document.createElement('a')
    a.href = url; a.download = 'liquidity_report.json'; a.click()
    URL.revokeObjectURL(url)
  }

  return (
    <div className="p-6 space-y-4">
      <div className="flex items-center justify-between">
        <h1 className="text-xl font-bold text-slate-800">Liquidity Risk Summary</h1>
        <div className="flex gap-2">
          <button
            onClick={copy}
            className="rounded-lg border border-slate-300 px-4 py-1.5 text-sm text-slate-700 hover:bg-slate-50 transition-colors"
          >
            Copy text
          </button>
          <button
            onClick={downloadJSON}
            className="rounded-lg bg-blue-600 px-4 py-1.5 text-sm font-semibold text-white hover:bg-blue-700 transition-colors"
          >
            Download JSON
          </button>
        </div>
      </div>

      <pre className="rounded-xl bg-slate-900 text-green-300 p-6 text-xs leading-relaxed overflow-auto whitespace-pre-wrap font-mono shadow-inner">
        {narrative}
      </pre>
    </div>
  )
}
